[package]
name = "epitok-web"
version = "0.1.0"
authors = ["Philippe Loctaux <p@philippeloctaux.com>"]
edition = "2018"

[dependencies]
# web framework
actix-web = "2.0.0"
actix-rt = "1.1.1"
actix-files = "0.2.2"

# templating
askama = "0.10.3"

# environment
env_logger = "0.7.1"
log = "0.4.11"